theme: jekyll-theme-cayman
title: Welcome to DaletotheP's homepage!
description: There is a map of the music industry that I have in development and a geographic map of philanthropic and nonprofit organizations relative to the arts in New York. Feel free to bookmark this to keep an eye on my project updates
